### PR TITLE
Fixes and enhancements to inventory and crits/fumbles.

### LINKED ISSUE #68: Provide a way to mark armor as unequipped
Now multiple items of armor can be worn it would be nice to be able to unequip to indicate armor that is being carried but not worn.

### LINKED ISSUE #71: Restore scroll position when editing items
Foundry has a mechanism for capturing and restoring the scroll position of a sheet. We don't currently implement this so it snaps to the top when editing equipment making this a frustrating operation.

### LINKED ISSUE #73: Correctly highlight die results when rolling under
Luck die currently shows a 1 as red and a 20 as green.

### LINKED ISSUE #74: Add a checkbox for lost spells
A checkbox next to each spell on the spells sheet could indicate when a spell is lost

### LINKED ISSUE #75: Support custom crit and fumble tables
Currently the tables to use for crits and fumbles are hardcoded.

### PR DESCRIPTION
**Pull request by mooped**
Hide irrelevant settings in the configuration dialog for NPC sheets.
Provide an interface for rolls to specify special highlighting rules.
Highlight deed rolls and luck checks correctly. Closes #73.
Expose a checkbox to unequip armor. Unequipped armor doesn't count towards fumbles or AC calculations. Closes #68.
Migration to ensure that items default to equipped (previous default was unequipped from before the field was used).
Declutter zero level sheet by removing the description field on armor - zeroes are unlikely to have very special armor and on the narrow sheet this made the rest of the armor fields unusable.
Spells now have an 'available' field, this defaults to true. Wizard spells sheet shows a checkbox for this so lost spells can be marked unavailable. Currently this has no other effect. Closes #74.
Character sheets provide Foundry with the information necessary to maintain the scroll position, making editing the inventory much less frustrating. Closes #71.
Custom critical hit and fumble tables can be configured in the system settings. For crits a compendium is specified and the table is looked up based on the name. For fumbles a single table is specified. Closes #75.
Removed built in crit and fumble tables.

### CODE REVIEW

**Comment by cyface** [comment]
@mooped Let me know when this is ready to merge! 💯

**Comment by mooped** [comment]
> @mooped Let me know when this is ready to merge! 💯

I'm pretty confident in it, but I noticed an existing issue with NPC import (ranged weapons come in broken, disappear on a reload) that I'd like to fix before making a new release.

It would also be nice to source some new icons for the hotbar macros before making a release if possible. Maybe white with a black border for contrast.

I made a list of the current macros and ideas for icons in issue #59 where the contrast issue was mentioned.

**Comment by mooped** [comment]
I've done a bit more testing and everything looks good, so feel free to merge this. :)

I can't reproduce the issue I mentioned with NPC imports, though I did make a minor tweak so 'missile' attacks also get marked as ranged.

**Comment by cyface** [comment]
Sounds good! I have released it!

**Pull request merged**
